export const emptyOffice = {
  baCode: '',
  affiliateBa: '',
  branch: '',
  place: '',
};

export const emptyDraft = {
  savedAt: null,
  office: { ...emptyOffice },
  kyc: {
    ckycNo: '',
    customerId: '',
    pan: '',
    dob: '',
    gender: '',
    name: '',
    fatherName: '',
    motherName: '',
    spouseName: '',
    countryOfBirth: '',
    cityOfBirth: '',
    photo: '',
    commAddress: '',
    commCity: '',
    commState: '',
    commPin: '',
    commCountry: '',
    birthPlace: '',
    nationality: '',
    citizenship: '',
    permAddress: '',
    permCity: '',
    permState: '',
    permPin: '',
    maritalStatus: '',
    mobile: '',
    email: '',
    category: '',
    occupation: '',
    occupationOther: '',
    businessNature: '',
    businessOther: '',
    pep: '',
    annualIncome: '',
    sourceOfFund: [],
    sourceOther: '',
    differentlyAbled: '',
    poiType: '',
    poiIdNo: '',
    poiExpiry: '',
    poaType: '',
    poaExpiry: '',
    taxResidentIndiaOnly: false,
    taxResidentOther: false,
    taxRows: [
      { country: '', tin: '', idType: '', addressType: [], addrKind: [], pin: '', state: '', countryAddr: '' },
    ],
    declPlace: '',
    declDate: '',
  },
  fd: {
    periodMonths: '',
    freshUtr: '',
    amount: '',
    drawnOn: '',
    chequeDate: '',
    oldCertNo: '',
    maturityDate: '',
    renewalAmount: '',
    partRefund: '',
    totalInvestment: '',
    depositType: '',
    receiptType: '',
    maturityInstruction: '',
    modeOfOperation: '',
    scheme: '',
    seniorCitizen: '',
    minor: '',
    first: {
      form97: false,
      form12f: '',
    },
    second: {
      title: '',
      name: '',
      ckyc: '',
      dob: '',
      pan: '',
      form97: false,
      customerId: '',
      email: '',
      mobile: '',
    },
    guardian: {
      title: '',
      name: '',
      ckyc: '',
      ofApplicant: '',
      dob: '',
      pan: '',
      customerId: '',
      email: '',
      mobile: '',
      relation: '',
    },
    bankAccountNo: '',
    bankName: '',
    micr: '',
    bankBranch: '',
    ifsc: '',
    accountType: '',
    witness1Name: '',
    witness1Address: '',
    witness2Name: '',
    witness2Address: '',
    nominate: '',
    returnToDepositor: '',
    nomineeName: '',
    nomineeDob: '',
    nomineeAddress: '',
    nomineeCity: '',
    nomineePin: '',
    nomineeRelation: '',
    nomineeRelationOther: '',
    appointeeName: '',
    appointeeDob: '',
    appointeeAddress: '',
  },
};

export function mergeDraft(saved, officeFallback) {
  const office = { ...emptyOffice, ...(officeFallback || {}), ...(saved?.office || {}) };
  if (!saved) {
    const blank = structuredClone(emptyDraft);
    blank.office = office;
    return blank;
  }
  return {
    ...emptyDraft,
    ...saved,
    office,
    kyc: { ...emptyDraft.kyc, ...(saved.kyc || {}), taxRows: saved.kyc?.taxRows?.length ? saved.kyc.taxRows : emptyDraft.kyc.taxRows },
    fd: {
      ...emptyDraft.fd,
      ...(saved.fd || {}),
      first: { ...emptyDraft.fd.first, ...(saved.fd?.first || {}) },
      second: { ...emptyDraft.fd.second, ...(saved.fd?.second || {}) },
      guardian: { ...emptyDraft.fd.guardian, ...(saved.fd?.guardian || {}) },
    },
  };
}
